/*
Create database
*/

-- DROP TABLE USERS;
-- DROP TABLE CATEGORIES;
-- DROP TABLE LEDGER;

CREATE TABLE USERS (
	ID INT PRIMARY KEY NOT NULL,
	NAME TEXT NOT NULL
);

CREATE TABLE CATEGORIES (
	ID INT PRIMARY KEY NOT NULL,
	NAME TEXT NOT NULL
);

CREATE TABLE LEDGER (
	ID INT PRIMARY KEY NOT NULL,
	NAME INT NOT NULL,
	DATE CHAR(10) NOT NULL,
	CATEGORY INT NOT NULL,
	AMOUNT INT NOT NULL,
	DESCRIPTION TEXT
);

INSERT INTO USERS (0, "Colby");
INSERT INTO USERS (1, "Sarah");

INSERT INTO CATEGORIES (0, "Groceries");
INSERT INTO CATEGORIES (1, "Bills");
INSERT INTO CATEGORIES (2, "Food");
INSERT INTO CATEGORIES (3, "School");
INSERT INTO CATEGORIES (4, "Supplies");
INSERT INTO CATEGORIES (5, "Repair/Maintenance");
INSERT INTO CATEGORIES (6, "Fun");
INSERT INTO CATEGORIES (7, "Misc");